name: Build and Test
permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    branches:
     - "main"
    paths:
      - "src/Transmitly.TemplateEngine.Fluid/**"
jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/build-and-deploy-channel-provider.yml@main
    with: 
      channelProviderName: Transmitly.TemplateEngine.Fluid
    secrets: inherit

      
